config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :pages, only: %i[index] do
    collection do
      get :projects
      get :plantysecrets
      get :pawsome
      get :experiences
      get :parcours
      get :telecharger_pdf
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def default_url_options
        { host: ENV["DOMAIN"] || "localhost:3000" }
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def projects
  end
  
  def plantysecrets
  end

  def pawsome
  end

  def home
  end

  def experiences
  end
  
  def parcours
  end

  def telecharger_pdf
    send_file(
      "#{Rails.root}/public/CV-anna-mahe.pdf",
      filename: "CV-anna-mahe.pdf",
      type: "application/pdf"
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
end
  

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anna Mahe Portfolio</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
      <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    
    <%= favicon_link_tag 'am-white.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= yield %>
    <%= render "shared/buttons" %>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/ambitions.html.erb
<%# CAROUSEL %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="parcours-container">
        <h2>Mon parcours</h2>

        <div class="parcours-presentation">
          <p>Après avoir suivi une formation intensive de 9 semaines en développement web au sein de l’organisme du Wagon, je suis désormais prête à mettre mes compétences en pratique dans le monde professionnel. </p>
        </div>

        <div class="carousel-arrows-container">
          <div class="arrow-container">
            <button class="prev-arrow" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
          </div>
          <div id="carouselExampleControls" class="carousel slide parcours-carousel row" data-bs-ride="carousel">
            <div class="carousel-inner">

              <div class="carousel-item parcours-paragraph active" data-bs-interval="120000">
                <h4>D'où je viens</h4>
                <p> Vous l’aurez peut-être remarqué dans mes expériences professionnelles ou en regardant mon profil LinkedIn,
                  que j’ai un parcours pour le moins hétéroclite. J’ai su très vite que le monde de l’export et du commerce international
                  n’étaient pas faits pour moi, mais de là s’est posée la question: de quoi ai-je envie?
                </p>
                <p> Plusieurs expériences professionnelles se succèdent sans éveiller de grande passion. C’est en 2018, en découvrant
                  le métier d’intégratrice web de ma colocataire que ma curiosité est piquée. C’est en 2020, en suivant une formation
                  OpenClassroom sur Illustrator que mon attrait vers les métiers de l’informatique se confirme. Finalement, c’est en 2022,
                  en discutant de façon approfondie avec mon entourage que ma décision est prise: je commencerai une formation intensive chez Le Wagon en janvier 2023 !
                </p>
              </div>

              <div class="carousel-item parcours-paragraph" data-bs-interval="120000">
                <h4>Où je suis</h4>
                <p> A travers de nombreux cours, d’autant d’exercices et de pas mal de projets, j'ai acquis une expérience en programmation
                  que ce soit en back-end grâce au framework Ruby On Rails, ou en front-end en utilisant des langages tels que HTML, CSS,
                  JavaScript.
                </p>
                <p> En 9 semaines, je suis passée de novice inexpérimentée à une jeune développeuse capable de concevoir et de
                  créer des bases de données, d’interagir avec les données qui y sont présentes et d’y faire appel en suivant le modèle MVC
                  (Model - View - Controller). J'ai également travaillé sur des projets qui m’ont permis d’approfondir mes compétences en matière de
                  développement web et m'ont permis d'améliorer mes compétences en travail d'équipe et en résolution de problèmes.
                </p>
              </div>

              <div class="carousel-item parcours-paragraph" data-bs-interval="120000">
                <h4>Où je vais</h4>
                <p> Je suis convaincue que ma courbe d’apprentissage ne peut pas s’arrêter là, je garde une forte volonté d'apprendre
                  et de m'adapter aux nouvelles technologies. Mon ambition pour la suite est donc d’agrandir mon répertoire technique
                  grâce à de nouveaux langages en back-end (Node.js, Java) et en front-end (React, Angular).
                </p>
                <p> Mon objectif idéal serait de réussir à intégrer une équipe prête à me donner ma chance et de travailler dur pour
                  réaliser avec succès les tâches qui me sont confiées.
                </p>
              </div>
            </div>
          </div>
          <div class="arrow-container">
            <button class="next-arrow" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>


        <div class="parcours-presentation">
          <p>Alors n’hésitez pas à me contacter sur LinkedIn où à m’envoyer un mail, les deux sont dans le footer 🙂 </p>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/pages/experiences.html.erb
<!-- EXPERIENCES -->

<div class="container experiences-container">
  <h2 class="mt-5">Expériences professionnelles</h2>
  <div class="experiences row row-cols-1 row-cols-md-3 g-3">

    <div class="col">
      <div class="card align-items-center card-experience">
        <%= image_tag "experiences/professeure.png" %>
        <div class="card-body">
          <h5 class="card-title">Professeure d'anglais</h5>
          <div class="card-footer">
            <small class="text-muted">2022</small>
          </div>
          <p class="card-text">Préparation des cours, suivi des avancées des élèves, évaluations régulières grâce à Quizlet, travail avec Ecole Directe.</p>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card align-items-center card-experience">
        <%= image_tag "experiences/vendeuse.png" %>
        <div class="card-body">
          <h5 class="card-title">Assistante Export Maisons du Monde</h5>
          <div class="card-footer">
            <small class="text-muted">2020 - 2021</small>
          </div>
          <p class="card-text">Chargée du suivi logistique et commercial des expéditions vers les magasins hors Europe.</p>
          <p class="card-text">Gestion des commandes exceptionnelles et éligibilités produits.</p>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card align-items-center card-experience">
        <%= image_tag "experiences/technicienne.png" %>
        <div class="card-body">
          <h5 class="card-title">Technicienne Apple</h5>
          <div class="card-footer">
            <small class="text-muted">2018 - 2019</small>
          </div>
          <p class="card-text">Accueil et traitement des incidents logiciels iOS à distance, réalisation des installations de logiciels, d'applicatifs et mises à jours.</p>
          <p class="card-text">Reporting de ses activités dans l’outil mis à disposition.</p>
        </div>
      </div>
    </div> 
  </div>

  <!-- FORMATIONS -->

  <div class="formations-container">
    <h2 class="ms-4">Formations</h2>
    <div class="experiences row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">

      <div class="col">
        <div class="card align-items-center card-experience">
          <%= image_tag "formations/wagon.png" %>
          <div class="card-body">
            <h5 class="card-title">Conception et Développement d'Applications Web</h5>
            <div class="card-footer">
              <small class="text-muted">2023</small>
            </div>
            <p class="card-text">Accueil et traitement des incidents logiciels iOS à distance, réalisation des installations de logiciels, d'applicatifs et mises à jours.</p>
            <p class="card-text">Reporting de ses activités dans l’outil mis à disposition.</p>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="card align-items-center card-experience">
          <%= image_tag "formations/master.png" %>
          <div class="card-body">
            <h5 class="card-title">Master Responsable Développement International</h5>
            <div class="card-footer">
              <small class="text-muted">2016-2018</small>
            </div>
            <p class="card-text">Exportation d'entreprises à l'échelle européenne et suivi apprentissage des douanes internationales.</p>
            <p class="card-text">Expatriation de 9 mois en Nouvelle-Zélande en 2017.</p>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="card align-items-center card-experience">
          <%= image_tag "formations/licence.png" %>
          <div class="card-body">
            <h5 class="card-title">Licence Langues Etrangères Appliquées</h5>
            <div class="card-footer">
              <small class="text-muted">2012-2015</small>
            </div>
            <p class="card-text">Suivi des cours, apprentissage approfondi de l'anglais et de l'espagnole ainsi que de leurs économies nationales respectives.</p>
            <p class="card-text">Erasmus de 6 mois en Espagne.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- BANNER  -->
<div class="home-container">
  <div class="home-banner">
    <div class="home-row">
      <h1>Anna Mahé</h1>
      <h5><span data-controller="typed-js"></span></h5>
      <p>Suite à ma formation en développement web au Wagon, je suis prête à mettre en pratique mes compétences en
        programmation en back-end et front-end. Mon objectif est d'élargir mes connaissances en utilisant de nouveaux
        langages.
      </p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <!-- TECHNOLOGIES -->
      <div class="main-container">
        <h2>Technologies</h2>
        <div class="cards language-categories d-flex">
          
          <div class="language-category">
            <p class="text-center">Front-end</p>
            <div class="col cards-category d-flex">
              <div class="language">
                <%= image_tag "languages/html5.png", class: "card-img-top" %>
                <div class="card-body-category">
                  <p class="card-language-text">HTML5</p>
                </div>
              </div>
              <div class="language">
                <%= image_tag "languages/css3.png", class: "card-img-top" %>
                <div class="card-body-category">
                  <p class="card-language-text">CSS3</p>
                </div>
              </div>
              <div class="language">
                <%= image_tag "languages/javascript.png", class: "card-img-top" %>
                <div class="card-body-category">
                  <p class="card-language-text">Javascript</p>
                </div>
              </div>
              <div class="language">
                <%= image_tag "languages/react.png", class: "card-img-top" %>
                <div class="card-language">
                  <p class="card-language-text">React</p>
                </div>
              </div>
            </div>
          </div>
          <div class="language-category">
            <p class="text-center">Back-end</p>
            <div class="col cards-category d-flex">
              <div class="language">
                <%= image_tag "languages/ruby-on-rails.png", class: "card-img-top" %>
                <div class="card-body-category">
                  <p class="card-language-text">Ruby On Rails</p>
                </div>
              </div>
              <div class="language">
                <%= image_tag "languages/ruby.png", class: "card-img-top" %>
                <div class="card-body-category">
                  <p class="card-language-text">Ruby</p>
                </div>
              </div>
              <div class="language">
                <%= image_tag "languages/nodejs.png", class: "card-img-top" %>
                <div class="card-body-category">
                  <p class="card-language-text">Node.js</p>
                </div>
              </div>
            </div>
          </div>
          <div class="language-category">
            <p class="text-center">Workflow</p>
            <div class="col cards-category d-flex">
              <div class="language">
                <%= image_tag "languages/figma.png", class: "card-img-top" %>
                <div class="card-body-category">
                  <p class="card-language-text">Figma</p>
                </div>
              </div>
                <div class="language">
                  <%= image_tag "languages/git.png", class: "card-img-top" %>
                  <div class="card-body-category">
                    <p class="card-language-text">Git</p>
                  </div>
                </div>
                <div class="language">
                  <%= image_tag "languages/notion.png", class: "card-img-top" %>
                  <div class="card-body-category">
                    <p class="card-language-text">Notion</p>
                  </div>
                </div>
              </div>
          </div>
          <div class="language-category">
            <p class="text-center">Bases de données</p>
            <div class="col cards-category d-flex">
                <div class="language">
                    <%= image_tag "languages/sql.png", class: "card-img-top" %>
                    <div class="card-body-category">
                        <p class="card-language-text">SQL</p>
                    </div>
                </div>
                <div class="language">
                    <%= image_tag "languages/postgresql.png", class: "card-img-top" %>
                    <div class="card-body-category">
                        <p class="card-language-text">PostgreSQL</p>
                    </div>
                </div>
              </div>
          </div>
        </div>

        <!-- PROJECTS -->
        <h2>Mes projets</h2>
        <div class="projects-cards" id="projects">

          <div class="project">
            <%= image_tag "projects/planty-secrets.png" %>
            <div class="infos">
              <h4>Planty Secrets</h4>
              <p>Projet final à la sortie du Wagon</p>
              <div class="site-link">
                <i class="fa-solid fa-angles-down"></i>
              </div>
              <div class="project-infos flop">
                <div class="bullet-point">
                    <i class="fa-solid fa-comment fa-flip-horizontal icons"></i>
                    <p>Reconnaissance des plantes et de leurs vertus médicales</p>
                </div>
                <div class="bullet-point">
                    <i class="fa-solid fa-calendar-days icons"></i>
                    <p>10 jours</p>
                </div>
                <div class="bullet-point">
                    <i class="fa-solid fa-users icons"></i>
                    <p>3 personnes</p>
                </div>
                <div class="bullet-point">
                    <i class="fa-solid fa-laptop-code icons"></i>
                    <p>Téléphone</p>
                </div>
                <div class="button">
                  <%= link_to "En savoir plus", plantysecrets_pages_path %>
                </div>
              </div>
            </div>
          </div>

          <div class="project">
            <%= image_tag "projects/pawesome.png", class: "pt-5" %>
            <div class="infos">
              <h4>Pawsome</h4>
              <p>Projet intermédiaire type e-commerce</p>
              <div class="site-link">
                <i class="fa-solid fa-angles-down"></i>
              </div>
              <div class="project-infos flop">
                <div class="bullet-point">
                    <i class="fa-solid fa-comment fa-flip-horizontal icons"></i>
                    <p>Location d'animaux exotiques en tous genres</p>
                </div>
                <div class="bullet-point">
                    <i class="fa-solid fa-calendar-days icons"></i>
                    <p>4 jours</p>
                </div>
                <div class="bullet-point">
                    <i class="fa-solid fa-users icons"></i>
                    <p>3 personnes</p>
                </div>
                <div class="bullet-point">
                    <i class="fa-solid fa-laptop-code icons"></i>
                    <p>Ordinateur</p>
                </div>
                <div class="button">
                  <%= link_to "En savoir plus", pawsome_pages_path %>
                </div>
              </div>
            </div>
          </div>


          <div class="project">
            <%= image_tag "projects/recipes-manager.png" %>
            <div class="infos">
              <h4>Recipes Manager</h4>
              <p>Projet indépendant post formation</p>
              <div class="site-link">
                <i class="fa-solid fa-angles-down"></i>
              </div>
              <div class="project-infos flop">
                <div class="bullet-point">
                    <i class="fa-solid fa-comment fa-flip-horizontal icons"></i>
                    <p>Sauvegarde de nos recettes préférées</p>
                </div>
                <div class="bullet-point">
                    <i class="fa-solid fa-screwdriver-wrench icons"></i>
                    <p>Projet en cours</p>
                </div>
                <div class="bullet-point">
                    <i class="fa-solid fa-users icons"></i>
                    <p>1 personne</p>
                </div>
                <div class="bullet-point">
                    <i class="fa-solid fa-laptop-code icons"></i>
                    <p>Ordinateur & Téléphone</p>
                </div>
                <%# <div class="button">
                  <%= link_to "En savoir plus", pawsome_pages_path %>
                <%# </div>  %>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/pages/parcours.html.erb
<%# CAROUSEL %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="main-container">
        <h2>Mon parcours</h2>

        <div class="carousel-arrows-container">
          <div class="arrow-container">
            <button class="prev-arrow" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
          </div>
          <div id="carouselExampleControls" class="carousel slide parcours-carousel row" data-bs-ride="carousel">
            <div class="carousel-inner">

              <div class="carousel-item parcours-paragraph active" data-bs-interval="120000">
                <h4>D'où je viens</h4>
                <p> Vous l’aurez peut-être remarqué dans mes expériences professionnelles ou en regardant mon profil LinkedIn,
                  que j’ai un parcours pour le moins hétéroclite. J’ai su très vite que le monde de l’export et du commerce international
                  n’étaient pas faits pour moi, mais de là s’est posée la question: de quoi ai-je envie?
                </p>
                <p> Plusieurs expériences professionnelles se succèdent sans éveiller de grande passion. C’est en 2018, en découvrant
                  le métier d’intégratrice web de ma colocataire que ma curiosité est piquée. C’est en 2020, en suivant une formation
                  OpenClassroom sur Illustrator que mon attrait vers les métiers de l’informatique se confirme. Finalement, c’est en 2022,
                  en discutant de façon approfondie avec mon entourage que ma décision est prise: je commencerai une formation intensive chez Le Wagon en janvier 2023 !
                </p>
              </div>

              <div class="carousel-item parcours-paragraph" data-bs-interval="120000">
                <h4>Où je suis</h4>
                <p> A travers de nombreux cours, d’autant d’exercices et de pas mal de projets, j'ai acquis une expérience en programmation
                  que ce soit en back-end grâce au framework Ruby On Rails, ou en front-end en utilisant des langages tels que HTML, CSS,
                  JavaScript.
                </p>
                <p> En 9 semaines, je suis passée de novice inexpérimentée à une jeune développeuse capable de concevoir et de
                  créer des bases de données, d’interagir avec les données qui y sont présentes et d’y faire appel en suivant le modèle MVC
                  (Model - View - Controller). J'ai également travaillé sur des projets qui m’ont permis d’approfondir mes compétences en matière de
                  développement web et m'ont permis d'améliorer mes compétences en travail d'équipe et en résolution de problèmes.
                </p>
              </div>

              <div class="carousel-item parcours-paragraph" data-bs-interval="120000">
                <h4>Où je vais</h4>
                <p> Je suis convaincue que ma courbe d’apprentissage ne peut pas s’arrêter là, je garde une forte volonté d'apprendre
                  et de m'adapter aux nouvelles technologies. Mon ambition pour la suite est donc d’agrandir mon répertoire technique
                  grâce à de nouveaux langages en back-end (Node.js, Java) et en front-end (React, Angular).
                </p>
                <p> Mon objectif idéal serait de réussir à intégrer une équipe prête à me donner ma chance et de travailler dur pour
                  réaliser avec succès les tâches qui me sont confiées.
                </p>
              </div>
            </div>
          </div>
          <div class="arrow-container">
            <button class="next-arrow" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>


        <div class="parcours-presentation">
          <p id="end-presentation">Alors n’hésitez pas à me contacter sur LinkedIn où à m’envoyer un mail, les deux sont dans le footer 🙂 </p>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/pages/pawsome.html.erb
<div class="main-container">
    <h1> <a href="/#projects"><i class="fa-solid fa-angle-left back-button"></i></a> Bienvenue sur le projet Pawsome</h1>
    <div class="homepage">
        <a href="https://pawsome-annamahe9.herokuapp.com/" target="_blank"> <%= image_tag "projects/pawsome-homepage.png", class:"pawsome-homepage" %></a>
    </div>
    <div class="pawsome-presentation-paragraph">
        <p>Projet intermédiaire du bootcamp, Pawsome est un site type market place qui permet de louer des animaux exotiques entre particuliers. 
        Vous pouvez vous inscrire et louer des animaux rares ainsi qu'ajouter vous-même votre collection personnelle.</p>
        <p>Bien évidemment, même si cela n'est pas un projet "sérieux", cela nous a permis de mieux appréhender la conception d'un site internet, tout en étant challengé sur le temps (cela s'est fait en 4 jours de codage !)</p>
    </div>

    <p>Vous souhaitez partager votre tarantule ou louer un dragon de Komodo?</p>

    <div class="button">
        <a href="https://pawsome-annamahe9.herokuapp.com/" target="_blank" >C'est par ici !</a>
    </div>

</div>

app/views/pages/plantysecrets.html.erb
<div class="main-container">
  <h1> <a href="/#projects"><i class="fa-solid fa-angle-left back-button"></i></a> Bienvenue sur le projet Planty Secrets</h1>
  <div class="planty-project-details">

        <div class="planty-homepage-container">
            <a href="https://www.planty-secrets.site" target="_blank"> <%= image_tag "projects/planty-homepage.png", class:"planty-homepage" %></a>
        </div>

        <div id="planty-paragraphs">
            <p>Projet de fin de bootcamp et surtout web application créée pour des <strong>téléphones portables</strong>, Planty-Secrets est une application qui non seulement reconnaît les plantes grâce à une photo, 
                mais est également capable de donner les vertus médicinales de ces plantes ! Vous pouvez par la suite mettre les plantes qui vous intéressent en favoris et créer des listes de plantes.
            </p>

            <div class="planty-alert text-center">
                <p>Il n'existe qu'un utilisateur test à ce jour.</p>
                <i class="fa-solid fa-at" style="color: #00ffff;"></i> chanchandu44@yahoo.com
                <br>
                <i class="fa-solid fa-key fa-flip-both" style="color: #00ffff;"></i> 123456
                </div>
                <p class="text-center">Vous souhaitez en savoir plus sur les vertus médicales des plantes?</p>
                <div class="button" id="planty-project-button">
                    <%= image_tag "projects/planty-qr-code.png", class:"planty-qrcode" %>
                    <a href="https://www.planty-secrets.site" target="_blank" >C'est par ici !</a>
                </div>
                <div class="planty-recommendation">
                    <p class="text-center last-sentence">Pour une meilleure expérience, il est préférable de scanner le QR code depuis votre téléphone.</p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_buttons.html.erb
<div class="pill-buttons" id="download-button">
    <%= link_to 'CV', telecharger_pdf_pages_path, download: 'CV-anna-mahe.pdf' %>
</div>

<div class="pill-buttons" id="mail-button">
    <a href="mailto:annamahe9@gmail.com">Mail</a>
</div>

app/views/shared/_footer.html.erb
 <!-- FOOTER -->
<div class="footer">
  <a href="https://github.com/AnnaMahe9"><i class="fab fa-github"></i></a>
  <a href="https://www.linkedin.com/in/anna-mah%C3%A9/"><i class="fab fa-linkedin"></i></a>
</div>

app/views/shared/_navbar.html.erb
 <!-- NAVBAR -->
  <div class="navbar navbar-expand-sm navbar-light sticky-top navbar-lewagon">
      <div class="container-fluid">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "am-white.png" %>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <%= link_to "Mon parcours", parcours_pages_path, class:"navbar-link" %>
              </li>
              <li class="nav-item active">
                <a class="navbar-link" style="color: white;" href="/#projects">Mes projets</a>
              </li>
              <li class="nav-item">
                <%= link_to "Mes expériences", experiences_pages_path, class:"navbar-link" %>
              </li>
          </ul>
        </div>
      </div>
    </div>